apiVersion: v1
kind: Service
metadata:
  name: dotnet-endpoint-service
spec:
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: dotnet-endpoint
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dotnet-endpoint
  name: dotnet-endpoint-deployment
spec:
  selector:
    matchLabels:
      app: dotnet-endpoint
  replicas: 1
  template:
    metadata:
      labels:
        app: dotnet-endpoint
    spec:
      containers:
      - name: dotnet-endpoint
        image: dotnet-endpoint-service:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
